### ISSUE TITLE
现在我们需要的不是爬端口密码

### ISSUE THREAD

**Issue by William-Scott** [vxhly/node-ishadow-config#1]
我们连这个网站的网址都没法长期确定

**Comment by William-Scott** [comment]
用这个网址好像可以永久访问：http://ss.ishadowx.com/

**Comment by vxhly** [comment]
嗯~ o(*￣▽￣*)o，由于现在国内对这个ss 墙的蛮厉害的，所以这个项目已经算是废弃的项目了，我没有对其进行维护了，你完全可以fork我的源码进行修改，然后爬取得IP地址在`config/config.json`里面可以修改的
